server:
  port: 8080

spring:
  application:
    name: gitlab-webhook-processor

gitlab:
  api:
    credentials:
      url: https://gitlab.example.com/api/v4  # Replace with your GitLab instance URL
      token: YOUR_PRIVATE_ACCESS_TOKEN       # Replace with your token
  webhook:
    target-branches: main,develop
    api-spec-files: 
      - APISPEC/resolved/swagger.yml
      - APISPEC/unresolved/swagger.yml
